path:
  log: ./bpr/log.txt
  model: ./bpr/best_model
  result: ./bpr/metric.tsv

data:
  train: ./yelp2018/train.txt
  test: ./yelp2018/test.txt
  adj_mat: ./yelp2018/s_pre_adj_mat.npz

batch:
  train: 2048
  test: 1024

model:
  epochs: 1000
  n_layers: 4
  embed_dim: 64
  reg: 1.0e-4
  lr: 1.0e-3

loss: bpr

topk: 20
metrics: ['recall', 'ndcg', 'diversity']
rand_seed: 2024